default[:teamcity][:url]       = "http://localhost:8111/"
default[:teamcity][:user]      = "teamcity"
default[:teamcity][:path]      = "/usr/local/teamcity"
default[:teamcity][:version]   = "8.0.3"
default[:teamcity][:data_path] = "/var/teamcity"
